version: "3.8"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-tier
        
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "UrlShorter"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - app-tier

  shorter:
    image: leo/urlshorter
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_URLS=http://*:80;https://*:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_ENVIRONMENT=Release
    volumes:
      - C:\Users\790ma\.aspnet\https:/https
    depends_on:
      - redis
      - postgres
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge